---

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Generic Event Webhook 
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: DEMO-UI -      👓 Load parameters
  include_vars: ./00_config_cp4waiops.yaml




- name: DEMO-UI -      🚀 Create CP4WAIOPS Demo UI  
  kubernetes.core.k8s:
    state: present
    template: ./templates/waiops-demo-ui/create-cp4waiops-demo.j2
