

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Zen in Common Services being ready
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Zen in Common Services
# --------------------------------------------------------------------------------------------------------------------------------------

- name: TEST -          🚀 TEST
  shell: |
    oc get nodes
    oc get routes -n openshift-console console -o jsonpath={.spec.host}
    echo "test""
  register: zen_ready





